name: My first workflow 

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: list and Read files
          run: |
            cat echo "my first Github actions Job"
            ls -ltra
            cat README.md

        # - name: list files
        #   run: ls
          
        # - name: Read files
        #   run: cat README.md
          
          