name: Generate Ascii Artwork 

on: push 

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Install cowsay program
          run: sudo apt-get install cowsay -y

        - name: Cowsay program CMD
          run: cowsay -f dragon "Run for cover, I'm a Dragon....RAWR" >> dragon.txt
          
        - name: Test file exists
          run: grep -i "dragon" dragon.txt
        
        - name: Read file
          run: cat dragon.txt
        
        - name: Listout repo files
          run: ls  -ltra

          
          