name: Generate Ascii Artwork 

on: push 

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: Listout repo files
          run: ls  -ltra  

        - name: Running shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
          